name: Hello World Workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Enter your username"
        required: true
        default: "World"
      verdadeirooufalse:
        description: "Verdadeiro ou falso"
        required: true
        type: boolean
        default: "false"
      environment:
        description: "Enter your username"
        required: true
        default: ""
      seilaoque:
        description: "Enter your username"
        required: true
        default: ""
      blablabla:
        description: "Enter your username"
        required: true
        default: ""

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World with Username
        run: |
          echo "Hello, ${{ github.event.inputs.username }}!"
          echo "Hello, ${{ github.event.inputs.verdadeirooufalse }}!"
          echo "Hello, ${{ github.event.inputs.environment }}!"
          echo "Hello, ${{ github.event.inputs.seilaoque }}!"
          echo "Hello, ${{ github.event.inputs.blablabla }}!"
